feat: Updates client to accept other error response types
stone-payments/merchant-go-stone-openbank pull request #1
Opened 2022-11-30 18:10 UTC by anapolima

# General Pull Request

## Motivo da mudança
1. Possibilitar ao openbank client retornar detalhes de erros de requests feitas para outras APIs.

## Links das demandas que estão sendo resolvidas com a mudança.
1. https://app.clickup.com/t/376fqe4

## Checklist
- [ ] Doc updated
- [x] I followed the message commit specification described in CONTRIBUTING.md
- [ ] PR description updated with stage evidences
- [ ] Env_vars correctly updated

## Descreva como foi o teste e coloque em anexo as evidências.
> Notes: Inclua evidências sobre mudanças nas envs, na doc e atualize com evidências de stage!

1. Foram executados testes unitários
1.1. 
![image](https://user-images.githubusercontent.com/63270651/204874668-a1540a4f-dfb3-4a59-a11e-29a4b4fb5d85.png)

2022-11-30 18:30 UTC, GilbertoVGL requested changes

2022-11-30 18:30 UTC, GilbertoVGL commented on client.go
> +		}
A gente pode mover essa lógica para uma nova função do tipo `parseBody(v interface{}) error` e aí nós chamamos ela aqui no caso de erro, e na outra função em caso de sucesso

2022-11-30 18:30 UTC, GilbertoVGL commented on client.go
> +	ok, err := CheckResponse(resp, errorResponse)
```suggestion
	err := CheckResponse(resp, errorResponse)
```
Acho que aqui a gente pode retornar só o erro, sem o booleano

2022-11-30 18:30 UTC, GilbertoVGL commented on client.go
> +	if ok && successResponse != nil {
```suggestion
	if successResponse != nil {
```
aqui a gente pode remover o `ok`, já que se der erro no `CheckResponse` vai ser retornado logo abaixo dele na verificação.

2022-11-30 18:30 UTC, GilbertoVGL commented on client.go
> +func CheckResponse(r *http.Response, responseBody interface{}) (bool, error) {
```suggestion
func CheckResponse(r *http.Response, responseBody interface{}) error {
```
Tem um comentário abaixo explicando melhor, mas acho que aqui não precisamos retornar um booleano

2022-11-30 18:32 UTC, GilbertoVGL commented
Outra coisa que eu tinha em mente, era mantermos somente o que vamos usar: autenticação e lógica de requests. Acho que vale a pena fazer um levantamento do que é usado nessas operações e deletar todo o resto, ex.: `payment_invoice.go`, `payment.go`, etc.

Ver o que é essencial pra gente usar o `Do` e rancar fora o restante.

2022-12-02 14:06 UTC, GilbertoVGL reviewed
client.go:301
`AddAccountIdHeader` acho que não usamos, podemos remover também

2022-12-05 12:57 UTC, charllysonsouza commented on client.go
> +			if w, ok := body.(io.Writer); ok {
aqui você tenta converter o body para a interface `Writer`?

2022-12-05 13:37 UTC, GilbertoVGL requested changes

2022-12-05 13:37 UTC, GilbertoVGL commented on authentication.go
> +	_, err = c.Do(req, &token, new(TransferError))
```suggestion
	_, err = c.Do(req, &token, nil)
```

2022-12-05 13:37 UTC, GilbertoVGL commented on authentication.go
> +	_, err = c.Do(req, &token, new(TransferError))
Motivo: o método `Do` já retorna um erro que é usado no retorno, o próprio retorno do método `Do` é um `ErrorResponse` que contém um `TransferError`, não precisamos passar uma referência que não será utilizada.

2022-12-05 13:37 UTC, GilbertoVGL commented on client.go
> +		if body != nil {
```suggestion
	if len(data) > 0 && body != nil {
```

2022-12-05 13:37 UTC, GilbertoVGL commented on client.go
>  	}
Sugestão:
```
if err == nil {
	if err := parseBody(data, errorBody); err != nil {
		errorResponse.Message = string(data)
	}

	errorResponse.TransferError = errorBody
}
```

2022-12-05 13:37 UTC, GilbertoVGL commented on client.go
>  	}
Sugestão pro if da linha 246

2022-12-05 13:37 UTC, GilbertoVGL commented on client.go
>  	}
```
if err := parseBody(data, successResponse); err != nil {
	return response, err
}
```

2022-12-05 13:37 UTC, GilbertoVGL commented on client.go
>  	}
Da linha 329

2022-12-05 13:44 UTC, GilbertoVGL commented
Recomendo rodar um `go mod tidy`

2022-12-05 13:48 UTC, GilbertoVGL commented
Suspeito que o arquivo `webhook.go` não é usado no nosso contexto, pode confirmar?

Eu fiz uma busca pelo projeto das funções declaradas nesse arquivo e aparentemente as funções ali declaradas são usadas somente internamente, nenhuma outra função do pacote chama essas funções, e até onde me recordo, nós não utilizamos nenhuma das funções exportadas ali.

2022-12-05 15:08 UTC, lorytins commented on .github/PULL_REQUEST_TEMPLATE.md
> +> Notes: Inclua envidências sobre mudanças!
```suggestion
> Notes: Inclua evidências sobre mudanças!
```

2022-12-05 15:14 UTC, lorytins commented
O método AddIdempotencyHeader, no arquivo client linha 288, não está sendo usado em lugar nenhum. Será que ele terá alguma utilidade?

2022-12-05 15:14 UTC, lorytins reviewed
O método AddIdempotencyHeader, no arquivo client linha 288, não está sendo usado em lugar nenhum. Será que ele terá alguma utilidade?

2022-12-05 15:18 UTC, charllysonsouza commented
Pelo que vi o arquivo `common.go` não é utilizado em nenhum lugar, poderia ser deletado também.

2022-12-05 15:22 UTC, GilbertoVGL commented
> O método AddIdempotencyHeader, no arquivo client linha 288, não está sendo usado em lugar nenhum. Será que ele terá alguma utilidade?

Na avaliação que eu tinha feito eu notei que ele não era utilizado, mas pensei que pode ser que em algum momento utilizaremos, dado todo esse contexto de comunicação async que estamos fazendo.

2022-12-05 17:06 UTC, anapolima commented on authentication.go
> +	_, err = c.Do(req, &token, new(TransferError))
Entendi o seu ponto mas não sei se concordo. Dado que o atributo `TransferError` do `ErrorResponse` agora é uma interface, e seu valor é igual ao de `errorBody` na função `CheckResponse`, se for passado um valor `nil` pro método `Do`, esse valor será repassado como `nil` para o `errorBody` do `CheckResponse` e nós perdemos a informação do corpo da resposta novamente. A não ser que, em `parseBody`, façamos de `TransferError` um valor padrão para desserialização do corpo da requisição caso o `body` recebido por parâmetro seja `nil`, o que eu também acho que seja meio esquisito, já que `parseBody` é genérico, tanto pra requests de sucesso quanto de erro

2022-12-05 17:10 UTC, anapolima commented on client.go
> +			if w, ok := body.(io.Writer); ok {
exato

2022-12-06 16:02 UTC, lorytins approved these changes

2022-12-06 18:42 UTC, GilbertoVGL commented on authentication.go
> +	_, err = c.Do(req, &token, new(TransferError))
@anapolima saquei, pode manter.

2022-12-06 18:50 UTC, GilbertoVGL approved these changes

2022-12-06 18:52 UTC, charllysonsouza approved these changes

2022-12-06 18:53 UTC, merged